# All hots to be monitored.
[[hosts]]
ref = "hostname1"
location = "http://127.0.0.1"
port = 8000
authType = "CSRF"
tokenHeaderKey = "X-CSRF-Token"
genTokenEndpoint = "/api/v1/csrf.json"
tokenKeyFromEndpoint = "csrf_token"

# [[hosts]]
# ref = "hostname2"
# location = "http://127.0.0.1"
# port = 8080
# authType = "CSRF"
# tokenHeaderKey = "X-CSRF-Token"
# genTokenEndpoint = "/api/v1/csrf"
# tokenKeyFromEndpoint = "csrf_token"

# [[hosts]]
# ref = "hostname3"
# location = "http://127.0.0.1"
# port = 8080
# authType = "CSRF"
# tokenHeaderKey = "X-CSRF-Token"
# genTokenEndpoint = "/api/v1/csrf"
# tokenKeyFromEndpoint = "csrf_token"


# All metrics to be measured.
[[metrics]]
name = "seq"

  [metrics.options]
  type = "Counter"
  description = "I am running since"

# [[metrics]]
# name = "openConnections"

#   [metrics.options]
#   type = "Gauge"
#   description = "Track the open connections in the system"

# [[metrics]]
# name = "resquestTimeHistogram"
  
#   [metrics.histogramOptions]
#   buckets = [
#     12.4,
#     13.2,
#     4.5
#   ]

#   [metrics.options]
#   type = "Histogram"
#   description = "Track the open connections in the system"

# [[metrics]]
# name = "resquestTimeHistogram2"
  
#   [metrics.histogramOptions]
#   exponentialBuckets = [
#     100,
#     2,
#     5
#   ]

#   [metrics.options]
#   type = "Histogram"
#   description = "Track the open connections in the system"

# [[metrics]]
# name = "cpu_temp"

#   [metrics.options]
#   type = "Gauge"
#   description = "This say how much hot is the cpu"


# Now you should define what metrics to take care of in what host
[[metricsForHost]]
hostRef = "hostname1"
metricRef = "seq"
url = "/api/v1/health.json"
httpMethod = "GET"
path = "/blockchain/head/seq"

# [[metricsForHost]]
# hostRef = "hostname1"
# metricRef = "resquestTimeHistogram"
# url = "/api/v1/network/connections"
# httpMethod = "GET"
# path = "connections"

# [[metricsForHost]]
# hostRef = "hostname1"
# metricRef = "resquestTimeHistogram2"
# url = "/api/v1/network/connections"
# httpMethod = "GET"
# path = "connections"

# [[metricsForHost]]
# hostRef = "hostname1"
# metricRef = "uptime"
# url = "/api/v1/health"
# httpMethod = "GET"
# path = "/blockchain/head/block_hash"

# [[metricsForHost]]
# hostRef = "hostname2"
# metricRef = "uptime"
# url = "/api/v1/health"
# httpMethod = "GET"
# path = "/blockchain/head/seq"

# [[metricsForHost]]
# hostRef = "hostname3"
# metricRef = "cpu_temp"
# url = "/api/v1/health"
# httpMethod = "GET"
# path = "/blockchain/head/seq"


# TODO(denisacostaq@gmail.com):
# if you refer(under "metrics_for_host") to a not previously defined host or metric it will be raise an error and the process will not start
# if in all your definition you not use some host or metric the process will raise a warning and the process will start normally.
