# All hots to be monitored.
[[hosts]]
ref = "hostname1"
location = "127.0.0.1"
port = 8080
authType = "CSRF"
tokenKey = "X-CSRF-Token"
genTokenEndpoint = "/api/v1/csrf"

[[hosts]]
ref = "hostname2"
location = "127.0.0.1"
port = 8081
authType = "CSRF"
tokenKey = "X-CSRF-Token"
genTokenEndpoint = "/api/v1/csrf"

[[hosts]]
ref = "hostname3"
location = "127.0.0.1"
port = 8083
authType = "CSRF"
tokenKey = "X-CSRF-Token"
genTokenEndpoint = "/api/v1/csrf"


# All metrics to be measured.
[[metrics]]
name = "uptime"

  [metrics.options]
  type = "Counter"
  description = "I am running since"

[[metrics]]
name = "cpu_temp"

  [metrics.options]
  type = "Gauge"
  description = "This say how much hot is the cpu"


# Now you should define what metrics to take care of in what host
[[metricsForHost]]
hostRef = "hostname1"
metric = "uptime"
url = "/api/v1.0/ut"
httpMethod = "GET"

[[metricsForHost]]
hostRef = "hostname2"
metric = "uptime"
url = "/api/v1.0/started_since"
httpMethod = "GET"

[[metricsForHost]]
hostRef = "hostname3"
metric = "cpu_temp"
url = "/api/v1.0/sensors"
path = "/cpu/temp"
httpMethod = "GET"


# TODO(denisacostaq@gmail.com):
# if you refer(under "metrics_for_host") to a not previously defined host or metric it will be raise an error and the process will not start
# if in all your definition you not use some host or metric the process will raise a warning and the process will start normally.