#!/bin/bash
docker volume create --driver local \
                     --opt type=none \
                     --opt o=bind \
                     --opt device=/integration/skycoin/tomlconfig \
                     rextporter-config

docker volume create skycoin-data
docker volume create skycoin-wallet