#!/bin/bash
docker volume create --driver local \
                     --type=none \
                     --opt o=bind \
                     --opt device=$(PWD)/test/integration/skycoin/tomlconfig \
                     rextporter-config

docker volume create skycoin-data
docker volume create skycoin-wallet