#!/bin/bash
docker volume create --driver local \
                     --opt o=bind \
                     --opt device=(pwd)/test/integration/skycoin/tomlconfig \
                     rextporter-config

docker volume create skycoin-data
docker volume create skycoin-wallet
docker volume ls